# Generated by Django 3.2.15 on 2022-09-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2001-06-19'),
            preserve_default=False,
        ),
    ]
